name: ch4_methods
comment: ''
tensorboard: True
log_dir: ./logs/
ckpt_dir: ./ckpt/
seed: 9001
gpu: True
rgb: True
num_workers: 4
batch_size: 16
training:
  epochs: 100
  init_lr: 5.0e-3
  es: True
  delta: 0.5
  patience: 40
  best: True
  resume: False
retina:
  foveal_size: 37     
  n_patches: 2
  scaling: 10  #scale of successive patches
  std: 0.05
vars: #experimental variables
  fixloc: MHL3
  variant: 0 # 0:T123, 1:T123+curr, 2:T3+intermediate 3:T3+BN-LSTM