name: NONE
comment: ''
tensorboard: True
log_dir: ./logs/
ckpt_dir: ./ckpt/
seed: 9001
gpu: True
rgb: True
num_workers: 4
batch_size: 16
retina:
  foveal_size: 37     
  n_patches: 2
  scaling: 10  #scale of successive patches
  std: 0.05
AE:
  VAE: False
  BN: True
P1:            #phase 1 of training
  epochs: 250
  init_lr: 2.0e-3
  es: True
  delta: 0.005
  patience: 40
  resume: False
P2:            #phase 2 of training
  epochs: 0
  init_lr: 0
  es: True
  delta: 0
  patience: 0
  resume: False
P3:            #phase 3 of training
  epochs: 100
  init_lr: 5.0e-3
  es: True
  delta: 1.0
  patience: 30
  resume: False